-- Vila Nova PAF: production schema isolated from the other applications that
-- already share this Supabase project. All access goes through the paf-api
-- Edge Function with the service role; browser roles receive no table grants.

create extension if not exists pgcrypto;

create table public.paf_producers (
  id bigint generated by default as identity primary key,
  token text not null unique default encode(gen_random_bytes(18), 'hex'),
  name text not null,
  cpf text not null,
  cpf_digits text not null,
  phone text,
  address text,
  agency text,
  area_ha numeric(12, 3) not null default 0 check (area_ha >= 0),
  process_status text not null default 'INTERNALIZAR' check (process_status in ('INTERNALIZAR', 'INTERNALIZADO', 'APROVADO', 'PLANTADO', 'CANCELADO')),
  planting_year integer check (planting_year is null or planting_year between 1980 and 2100),
  designer text,
  original_row integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_report_at timestamptz
);

create table public.paf_technicians (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text,
  email text,
  role text,
  region text,
  active boolean not null default true,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.paf_access_accounts (
  id bigint generated by default as identity primary key,
  name text not null,
  login text not null unique check (login ~ '^[A-Z0-9._-]{3,60}$'),
  access_code_hash text not null,
  code_hint text,
  account_type text not null check (account_type in ('ADMIN', 'PRODUTOR', 'TECNICO', 'ORGANIZACAO')),
  technician_id bigint references public.paf_technicians(id) on delete set null,
  organization text,
  active boolean not null default true,
  can_submit_reports boolean not null default false,
  can_manage_visits boolean not null default false,
  notes text,
  last_login_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.paf_access_account_producers (
  access_account_id bigint not null references public.paf_access_accounts(id) on delete cascade,
  producer_id bigint not null references public.paf_producers(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (access_account_id, producer_id)
);

create table public.paf_auth_sessions (
  id bigint generated by default as identity primary key,
  token_hash text not null unique check (length(token_hash) = 64),
  role text not null check (role in ('admin', 'access')),
  access_account_id bigint not null references public.paf_access_accounts(id) on delete cascade,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null
);

create table public.paf_login_attempts (
  attempt_key text primary key,
  attempts integer not null default 0 check (attempts >= 0),
  reset_at timestamptz not null,
  updated_at timestamptz not null default now()
);

create table public.paf_reports (
  id bigint generated by default as identity primary key,
  producer_id bigint not null references public.paf_producers(id) on delete cascade,
  report_date date not null default current_date,
  contact_phone text,
  process_status text check (process_status is null or process_status in ('INTERNALIZAR', 'INTERNALIZADO', 'APROVADO', 'PLANTADO', 'CANCELADO')),
  area_status text,
  address text,
  area_ha numeric(12, 3) check (area_ha is null or area_ha >= 0),
  planting_year integer check (planting_year is null or planting_year between 1980 and 2100),
  crop text,
  planting_date date,
  production_note text,
  needs_visit boolean not null default false,
  notes text,
  review_status text not null default 'PENDENTE' check (review_status in ('PENDENTE', 'EM ANÁLISE', 'VISITA PROGRAMADA', 'CONCLUÍDO', 'DEVOLVIDO')),
  technical_note text,
  reviewed_at timestamptz,
  reviewed_by text,
  submitted_by_access_id bigint references public.paf_access_accounts(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.paf_technical_visits (
  id bigint generated by default as identity primary key,
  report_id bigint references public.paf_reports(id) on delete set null,
  producer_id bigint not null references public.paf_producers(id) on delete cascade,
  status text not null default 'PROGRAMADA' check (status in ('PROGRAMADA', 'EM CAMPO', 'CONCLUÍDA', 'REPROGRAMADA', 'CANCELADA')),
  priority text not null default 'NORMAL' check (priority in ('NORMAL', 'ALTA', 'CRÍTICA')),
  scheduled_date date,
  technician text,
  objective text,
  result_note text,
  created_by_access_id bigint references public.paf_access_accounts(id) on delete set null,
  updated_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  completed_at timestamptz
);

create table public.paf_operational_tasks (
  id bigint generated by default as identity primary key,
  producer_id bigint references public.paf_producers(id) on delete cascade,
  report_id bigint references public.paf_reports(id) on delete set null,
  visit_id bigint references public.paf_technical_visits(id) on delete set null,
  title text not null,
  type text not null default 'OUTRO' check (type in ('RELATÓRIO', 'VISITA', 'DOCUMENTO', 'CONTATO', 'CAMPO', 'OUTRO')),
  status text not null default 'ABERTA' check (status in ('ABERTA', 'EM ANDAMENTO', 'BLOQUEADA', 'CONCLUÍDA', 'CANCELADA')),
  priority text not null default 'NORMAL' check (priority in ('NORMAL', 'ALTA', 'CRÍTICA')),
  assignee text,
  due_date date,
  notes text,
  created_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  completed_at timestamptz
);

create table public.paf_documents (
  id bigint generated by default as identity primary key,
  producer_id bigint references public.paf_producers(id) on delete cascade,
  report_id bigint references public.paf_reports(id) on delete set null,
  visit_id bigint references public.paf_technical_visits(id) on delete set null,
  task_id bigint references public.paf_operational_tasks(id) on delete set null,
  title text not null,
  category text not null default 'OUTRO' check (category in ('CONTRATO', 'IDENTIFICAÇÃO', 'CAR', 'DAP/CAF', 'LICENÇA', 'LAUDO', 'FOTO', 'COMPROVANTE', 'OUTRO')),
  status text not null default 'PENDENTE' check (status in ('PENDENTE', 'EM ANÁLISE', 'VALIDADO', 'REJEITADO', 'VENCIDO')),
  file_name text,
  file_mime text,
  file_size bigint check (file_size is null or file_size >= 0),
  storage_bucket text,
  storage_path text,
  uploaded_by text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  reviewed_at timestamptz
);

create table public.paf_fuel_drivers (
  id bigint generated by default as identity primary key,
  name text not null,
  cpf text,
  phone text,
  license_number text,
  license_category text,
  license_expires_at date,
  active boolean not null default true,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.paf_fuel_vehicles (
  id bigint generated by default as identity primary key,
  cost_center text,
  department text,
  category text,
  area text,
  vehicle text,
  plate text not null unique,
  driver_id bigint references public.paf_fuel_drivers(id) on delete set null,
  assigned_to text,
  quota_liters numeric(12, 3) check (quota_liters is null or quota_liters >= 0),
  fleet_type text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.paf_fuel_records (
  id bigint generated by default as identity primary key,
  source_key text not null unique,
  source_file text,
  source_row integer,
  year integer check (year is null or year between 2000 and 2100),
  month text,
  driver_id bigint references public.paf_fuel_drivers(id) on delete set null,
  driver text,
  plate text,
  vehicle_responsible text,
  served_date date,
  requested_liters numeric(12, 3) check (requested_liters is null or requested_liters >= 0),
  supplied_liters numeric(12, 3) check (supplied_liters is null or supplied_liters >= 0),
  km_start numeric(14, 3),
  km_end numeric(14, 3),
  km_driven numeric(14, 3),
  km_per_liter numeric(12, 4),
  requisition text,
  notes text,
  quantity numeric(12, 3),
  location text,
  quota_liters numeric(12, 3),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.paf_import_batches (
  id bigint generated by default as identity primary key,
  import_type text not null check (import_type in ('PRODUTORES', 'ABASTECIMENTO')),
  file_name text,
  rows_received integer not null default 0,
  rows_imported integer not null default 0,
  rows_rejected integer not null default 0,
  imported_by text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table public.paf_audit_logs (
  id bigint generated by default as identity primary key,
  actor_access_id bigint references public.paf_access_accounts(id) on delete set null,
  actor_name text,
  actor_role text,
  action text not null,
  entity_type text not null,
  entity_id text,
  ip_address text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create or replace function public.paf_set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger paf_producers_updated_at before update on public.paf_producers for each row execute function public.paf_set_updated_at();
create trigger paf_technicians_updated_at before update on public.paf_technicians for each row execute function public.paf_set_updated_at();
create trigger paf_access_accounts_updated_at before update on public.paf_access_accounts for each row execute function public.paf_set_updated_at();
create trigger paf_reports_updated_at before update on public.paf_reports for each row execute function public.paf_set_updated_at();
create trigger paf_visits_updated_at before update on public.paf_technical_visits for each row execute function public.paf_set_updated_at();
create trigger paf_tasks_updated_at before update on public.paf_operational_tasks for each row execute function public.paf_set_updated_at();
create trigger paf_documents_updated_at before update on public.paf_documents for each row execute function public.paf_set_updated_at();
create trigger paf_fuel_drivers_updated_at before update on public.paf_fuel_drivers for each row execute function public.paf_set_updated_at();
create trigger paf_fuel_vehicles_updated_at before update on public.paf_fuel_vehicles for each row execute function public.paf_set_updated_at();
create trigger paf_fuel_records_updated_at before update on public.paf_fuel_records for each row execute function public.paf_set_updated_at();

create index paf_producers_name_idx on public.paf_producers (lower(name));
create index paf_producers_cpf_digits_idx on public.paf_producers (cpf_digits);
create index paf_producers_status_idx on public.paf_producers (process_status);
create index paf_producers_agency_idx on public.paf_producers (agency);
create index paf_producers_designer_idx on public.paf_producers (designer);
create index paf_producers_last_report_idx on public.paf_producers (last_report_at desc nulls last);
create index paf_access_accounts_active_idx on public.paf_access_accounts (active, account_type);
create index paf_access_scope_producer_idx on public.paf_access_account_producers (producer_id, access_account_id);
create index paf_sessions_expires_idx on public.paf_auth_sessions (expires_at);
create index paf_reports_producer_created_idx on public.paf_reports (producer_id, created_at desc);
create index paf_reports_review_idx on public.paf_reports (review_status, created_at desc);
create index paf_visits_producer_date_idx on public.paf_technical_visits (producer_id, scheduled_date desc nulls last);
create index paf_visits_status_idx on public.paf_technical_visits (status, priority);
create index paf_tasks_status_due_idx on public.paf_operational_tasks (status, due_date);
create index paf_tasks_producer_idx on public.paf_operational_tasks (producer_id, created_at desc);
create index paf_documents_producer_idx on public.paf_documents (producer_id, created_at desc);
create index paf_documents_status_idx on public.paf_documents (status, category);
create index paf_fuel_drivers_active_idx on public.paf_fuel_drivers (active, lower(name));
create index paf_fuel_vehicles_driver_idx on public.paf_fuel_vehicles (driver_id);
create index paf_fuel_records_date_idx on public.paf_fuel_records (served_date desc);
create index paf_fuel_records_driver_idx on public.paf_fuel_records (driver_id, driver);
create index paf_fuel_records_plate_idx on public.paf_fuel_records (plate);
create index paf_fuel_records_year_month_idx on public.paf_fuel_records (year, month);
create index paf_fuel_records_location_idx on public.paf_fuel_records (location);
create index paf_audit_entity_idx on public.paf_audit_logs (entity_type, entity_id, created_at desc);
create index paf_audit_actor_idx on public.paf_audit_logs (actor_access_id, created_at desc);

alter table public.paf_producers enable row level security;
alter table public.paf_technicians enable row level security;
alter table public.paf_access_accounts enable row level security;
alter table public.paf_access_account_producers enable row level security;
alter table public.paf_auth_sessions enable row level security;
alter table public.paf_login_attempts enable row level security;
alter table public.paf_reports enable row level security;
alter table public.paf_technical_visits enable row level security;
alter table public.paf_operational_tasks enable row level security;
alter table public.paf_documents enable row level security;
alter table public.paf_fuel_drivers enable row level security;
alter table public.paf_fuel_vehicles enable row level security;
alter table public.paf_fuel_records enable row level security;
alter table public.paf_import_batches enable row level security;
alter table public.paf_audit_logs enable row level security;

revoke all on table
  public.paf_producers,
  public.paf_technicians,
  public.paf_access_accounts,
  public.paf_access_account_producers,
  public.paf_auth_sessions,
  public.paf_login_attempts,
  public.paf_reports,
  public.paf_technical_visits,
  public.paf_operational_tasks,
  public.paf_documents,
  public.paf_fuel_drivers,
  public.paf_fuel_vehicles,
  public.paf_fuel_records,
  public.paf_import_batches,
  public.paf_audit_logs
from anon, authenticated;

grant all on table
  public.paf_producers,
  public.paf_technicians,
  public.paf_access_accounts,
  public.paf_access_account_producers,
  public.paf_auth_sessions,
  public.paf_login_attempts,
  public.paf_reports,
  public.paf_technical_visits,
  public.paf_operational_tasks,
  public.paf_documents,
  public.paf_fuel_drivers,
  public.paf_fuel_vehicles,
  public.paf_fuel_records,
  public.paf_import_batches,
  public.paf_audit_logs
to service_role;

grant usage, select on all sequences in schema public to service_role;
revoke all on function public.paf_set_updated_at() from public, anon, authenticated;
grant execute on function public.paf_set_updated_at() to service_role;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'paf-documents',
  'paf-documents',
  false,
  6291456,
  array['application/pdf', 'image/jpeg', 'image/png', 'image/webp', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'application/vnd.ms-excel']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;
